import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import Product from './models/Product.js';

// Get the directory name of the current module
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables with absolute path
dotenv.config({ path: path.resolve(__dirname, '.env') });

// Define products data - 68 products across 8 categories
const products = [
  // MEN - 10 products
  {
    name: "Classic Cotton T-Shirt",
    description: "Premium quality cotton t-shirt with a comfortable fit. Perfect for everyday wear.",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500"],
    category: "Men",
    subCategory: "T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    bestSeller: true,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Slim Fit Denim Jeans",
    description: "Modern slim fit jeans with stretch comfort. Classic 5-pocket style.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=500"],
    category: "Men",
    subCategory: "Jeans",
    sizes: ["S", "M", "L", "XL", "XXL"],
    bestSeller: true,
    inStock: true,
    rating: 4.7,
  },
  {
    name: "Casual Oxford Shirt",
    description: "Elegant oxford shirt made from premium cotton. Perfect for both casual and formal occasions.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500"],
    category: "Men",
    subCategory: "Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    bestSeller: false,
    inStock: true,
    rating: 4.3,
  },
  {
    name: "Leather Biker Jacket",
    description: "Premium genuine leather biker jacket with modern styling.",
    price: 299.99,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500"],
    category: "Men",
    subCategory: "Jackets",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },
  {
    name: "Winter Puffer Jacket",
    description: "Warm and stylish puffer jacket for cold winter days.",
    price: 159.99,
    images: ["https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500"],
    category: "Men",
    subCategory: "Jackets",
    sizes: ["S", "M", "L", "XL", "XXL"],
    bestSeller: true,
    inStock: true,
    rating: 4.6,
  },
  {
    name: "Formal Dress Pants",
    description: "Classic formal dress pants with perfect crease.",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500"],
    category: "Men",
    subCategory: "Pants",
    sizes: ["S", "M", "L", "XL", "XXL"],
    bestSeller: false,
    inStock: true,
    rating: 4.4,
  },
  {
    name: "Cotton Polo Shirt",
    description: "Classic polo shirt with embroidered logo.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=500"],
    category: "Men",
    subCategory: "T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    bestSeller: false,
    inStock: true,
    rating: 4.2,
  },
  {
    name: "Linen Summer Shorts",
    description: "Lightweight linen shorts perfect for summer.",
    price: 44.99,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500"],
    category: "Men",
    subCategory: "Shorts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    bestSeller: false,
    inStock: true,
    rating: 4.1,
  },

  // WOMEN - 10 products
  {
    name: "Floral Summer Dress",
    description: "Beautiful floral print dress perfect for summer occasions.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500"],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: true,
    inStock: true,
    rating: 4.7,
  },
  {
    name: "Silk Blouse",
    description: "Elegant silk blouse with pearl buttons.",
    price: 119.99,
    images: ["https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=500"],
    category: "Women",
    subCategory: "Tops",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: false,
    inStock: true,
    rating: 4.6,
  },
  {
    name: "High-Waisted Jeans",
    description: "Classic high-waisted jeans with a flattering fit.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500"],
    category: "Women",
    subCategory: "Jeans",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },
  {
    name: "Leather Handbag",
    description: "Genuine leather handbag with multiple compartments.",
    price: 149.99,
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500"],
    category: "Women",
    subCategory: "Bags",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.9,
  },
  {
    name: "Evening Gown",
    description: "Stunning evening gown with elegant draping.",
    price: 299.99,
    images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500"],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L"],
    bestSeller: true,
    inStock: true,
    rating: 4.9,
  },
  {
    name: "Yoga Pants",
    description: "Comfortable yoga pants with high waistband.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500"],
    category: "Women",
    subCategory: "Pants",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: true,
    inStock: true,
    rating: 4.6,
  },


  // KIDS - 10 products
  {
    name: "Boys Denim Jeans",
    description: "Durable denim jeans for active kids.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1517438476312-10d79c077509?w=500"],
    category: "Kids",
    subCategory: "Jeans",
    sizes: ["XS", "S", "M", "L", "XL"],
    bestSeller: false,
    inStock: true,
    rating: 4.4,
  },
  {
    name: "Girls Pink Dress",
    description: "Adorable pink dress for special occasions.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=500"],
    category: "Kids",
    subCategory: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },
  {
    name: "Kids Shorts Set",
    description: "Pack of 3 casual shorts for boys.",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=500"],
    category: "Kids",
    subCategory: "Shorts",
    sizes: ["XS", "S", "M", "L"],
    bestSeller: false,
    inStock: true,
    rating: 4.3,
  },
  {
    name: "Girls Leggings",
    description: "Comfortable leggings with fun patterns.",
    price: 24.99,
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500"],
    category: "Kids",
    subCategory: "Pants",
    sizes: ["XS", "S", "M", "L"],
    bestSeller: false,
    inStock: true,
    rating: 4.2,
  },
  {
    name: "Kids Sneakers",
    description: "Sporty sneakers with velcro closure.",
    price: 44.99,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500"],
    category: "Kids",
    subCategory: "Shoes",
    sizes: ["XS", "S", "M", "L", "XL"],
    bestSeller: true,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Kids Pajama Set",
    description: "Soft cotton pajama set with fun prints.",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500"],
    category: "Kids",
    subCategory: "Sleepwear",
    sizes: ["XS", "S", "M", "L"],
    bestSeller: false,
    inStock: true,
    rating: 4.4,
  },
  {
    name: "Kids Sweatshirt",
    description: "Comfortable cotton sweatshirt with fun design.",
    price: 34.99,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500"],
    category: "Kids",
    subCategory: "Tops",
    sizes: ["XS", "S", "M", "L"],
    bestSeller: false,
    inStock: true,
    rating: 4.3,
  },
  {
    name: "Kids Winter Coat",
    description: "Warm winter coat for kids.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500"],
    category: "Kids",
    subCategory: "Jackets",
    sizes: ["XS", "S", "M", "L"],
    bestSeller: true,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Kids Socks Set",
    description: "Pack of 5 colorful socks for kids.",
    price: 14.99,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500"],
    category: "Kids",
    subCategory: "Accessories",
    sizes: ["S", "M", "L"],
    bestSeller: false,
    inStock: true,
    rating: 4.2,
  },


  // FOOTWEAR - 10 products
  {
    name: "Running Sneakers",
    description: "Lightweight running sneakers with cushioned sole.",
    price: 119.99,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500"],
    category: "Footwear",
    subCategory: "Sneakers",
    sizes: ["6", "7", "8", "9", "10", "11"],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },
  {
    name: "Leather Oxford Shoes",
    description: "Classic leather oxford shoes for formal occasions.",
    price: 149.99,
    images: ["https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=500"],
    category: "Footwear",
    subCategory: "Formal",
    sizes: ["7", "8", "9", "10", "11", "12"],
    bestSeller: false,
    inStock: true,
    rating: 4.6,
  },
  {
    name: "Summer Sandals",
    description: "Comfortable summer sandals with adjustable straps.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500"],
    category: "Footwear",
    subCategory: "Sandals",
    sizes: ["6", "7", "8", "9", "10", "11"],
    bestSeller: true,
    inStock: true,
    rating: 4.4,
  },
  {
    name: "Winter Boots",
    description: "Warm winter boots with waterproof construction.",
    price: 179.99,
    images: ["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=500"],
    category: "Footwear",
    subCategory: "Boots",
    sizes: ["7", "8", "9", "10", "11", "12"],
    bestSeller: true,
    inStock: true,
    rating: 4.7,
  },
  {
    name: "Canvas Slip-Ons",
    description: "Casual canvas slip-on shoes for everyday wear.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500"],
    category: "Footwear",
    subCategory: "Casual",
    sizes: ["6", "7", "8", "9", "10", "11"],
    bestSeller: false,
    inStock: true,
    rating: 4.3,
  },
  {
    name: "High Heels",
    description: "Elegant high heels with comfortable padding.",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500"],
    category: "Footwear",
    subCategory: "Heels",
    sizes: ["5", "6", "7", "8", "9"],
    bestSeller: true,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Sports Trainers",
    description: "Professional sports trainers for gym and workout.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500"],
    category: "Footwear",
    subCategory: "Sports",
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    bestSeller: true,
    inStock: true,
    rating: 4.7,
  },
  {
    name: "Flip Flops",
    description: "Lightweight flip flops for beach and pool.",
    price: 19.99,
    images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500"],
    category: "Footwear",
    subCategory: "Sandals",
    sizes: ["6", "7", "8", "9", "10", "11"],
    bestSeller: false,
    inStock: true,
    rating: 4.1,
  },


  // ACCESSORIES - 10 products
  {
    name: "Leather Belt",
    description: "Genuine leather belt with classic buckle.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500"],
    category: "Accessories",
    subCategory: "Belts",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: true,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Sports Watch",
    description: "Water-resistant sports watch with chronograph.",
    price: 199.99,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500"],
    category: "Accessories",
    subCategory: "Watches",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },
  {
    name: "Sunglasses",
    description: "UV protection sunglasses with polarized lenses.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500"],
    category: "Accessories",
    subCategory: "Sunglasses",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.6,
  },
  {
    name: "Leather Wallet",
    description: "Slim leather wallet with multiple card slots.",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=500"],
    category: "Accessories",
    subCategory: "Wallets",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.4,
  },
  {
    name: "Scarf",
    description: "Soft cashmere blend scarf for all seasons.",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=500"],
    category: "Accessories",
    subCategory: "Scarves",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.3,
  },
  {
    name: "Baseball Cap",
    description: "Adjustable baseball cap with embroidered logo.",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500"],
    category: "Accessories",
    subCategory: "Hats",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.2,
  },
  {
    name: "Leather Gloves",
    description: "Genuine leather gloves with thermal lining.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1584644701911-cd45b8b00bfa?w=500"],
    category: "Accessories",
    subCategory: "Gloves",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: false,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Backpack",
    description: "Stylish backpack with laptop compartment.",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500"],
    category: "Accessories",
    subCategory: "Bags",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.7,
  },


  // ELECTRONICS - 10 products
  {
    name: "Wireless Headphones",
    description: "Premium wireless headphones with noise cancellation.",
    price: 249.99,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500"],
    category: "Electronics",
    subCategory: "Audio",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.9,
  },
  {
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with powerful sound.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500"],
    category: "Electronics",
    subCategory: "Audio",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.6,
  },
  {
    name: "Smart Watch",
    description: "Feature-rich smartwatch with health tracking.",
    price: 299.99,
    images: ["https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500"],
    category: "Electronics",
    subCategory: "Wearables",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },
  {
    name: "Portable Charger",
    description: "20000mAh portable power bank with fast charging.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500"],
    category: "Electronics",
    subCategory: "Accessories",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "USB-C Hub",
    description: "Multi-port USB-C hub for laptops.",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1625842268584-8f3296236761?w=500"],
    category: "Electronics",
    subCategory: "Accessories",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.4,
  },
  {
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with precision tracking.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500"],
    category: "Electronics",
    subCategory: "Accessories",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.3,
  },
  {
    name: "Webcam",
    description: "HD webcam with built-in microphone.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500"],
    category: "Electronics",
    subCategory: "Accessories",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.5,
  },


  // HOME & LIVING - 10 products
  {
    name: "Throw Pillow Set",
    description: "Set of 2 decorative throw pillows.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=500"],
    category: "Home",
    subCategory: "Decor",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Area Rug",
    description: "Modern area rug with abstract pattern.",
    price: 149.99,
    images: ["https://images.unsplash.com/photo-1531835551805-16d864c8d311?w=500"],
    category: "Home",
    subCategory: "Rugs",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.7,
  },
  {
    name: "Table Lamp",
    description: "Modern table lamp with adjustable brightness.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500"],
    category: "Home",
    subCategory: "Lighting",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.4,
  },
  {
    name: "Bedding Set",
    description: "Luxury bedding set with duvet cover.",
    price: 199.99,
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500"],
    category: "Home",
    subCategory: "Bedding",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },
  {
    name: "Wall Clock",
    description: "Modern minimalist wall clock with silent movement.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=500"],
    category: "Home",
    subCategory: "Decor",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.3,
  },
  {
    name: "Candle Set",
    description: "Set of 3 scented soy candles.",
    price: 34.99,
    images: ["https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=500"],
    category: "Home",
    subCategory: "Decor",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.6,
  },
  {
    name: "Vase",
    description: "Elegant ceramic vase for flowers.",
    price: 44.99,
    images: ["https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=500"],
    category: "Home",
    subCategory: "Decor",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.2,
  },
  {
    name: "Curtain Panels",
    description: "Set of 2 thermal insulated curtain panels.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?w=500"],
    category: "Home",
    subCategory: "Window",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Storage Basket",
    description: "Woven storage basket with handles.",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500"],
    category: "Home",
    subCategory: "Storage",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.4,
  },


  // BEAUTY - 10 products
  {
    name: "Face Moisturizer",
    description: "Hydrating face moisturizer with SPF 30.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500"],
    category: "Beauty",
    subCategory: "Skincare",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.7,
  },
  {
    name: "Lipstick Set",
    description: "Set of 5 matte lipsticks in trending colors.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500"],
    category: "Beauty",
    subCategory: "Makeup",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.6,
  },
  {
    name: "Perfume",
    description: "Long-lasting Eau de Parfum with floral notes.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=500"],
    category: "Beauty",
    subCategory: "Fragrance",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },
  {
    name: "Hair Dryer",
    description: "Professional hair dryer with ionic technology.",
    price: 129.99,
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=500"],
    category: "Beauty",
    subCategory: "Haircare",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.5,
  },
  {
    name: "Face Mask Set",
    description: "Pack of 10 hydrating face masks.",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=500"],
    category: "Beauty",
    subCategory: "Skincare",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.4,
  },
  {
    name: "Makeup Palette",
    description: "24-color eyeshadow palette with shimmers.",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500"],
    category: "Beauty",
    subCategory: "Makeup",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.7,
  },
  {
    name: "Skincare Kit",
    description: "Complete skincare kit with cleanser, toner, and serum.",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500"],
    category: "Beauty",
    subCategory: "Skincare",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.6,
  },
  {
    name: "Nail Polish Set",
    description: "Set of 6 gel nail polishes.",
    price: 34.99,
    images:["https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=500"],
    category: "Beauty",
    subCategory: "Makeup",
    sizes: [],
    bestSeller: false,
    inStock: true,
    rating: 4.3,
  },
  {
    name: "Face Serum",
    description: "Vitamin C brightening serum.",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500"],
    category: "Beauty",
    subCategory: "Skincare",
    sizes: [],
    bestSeller: true,
    inStock: true,
    rating: 4.8,
  },

];

// Function to seed products
const seedProducts = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert new products
    await Product.insertMany(products);
    console.log(`Successfully seeded ${products.length} products`);

    // Disconnect from MongoDB
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
};

// Run the seed function
seedProducts();
